### ISSUE TITLE
TFDS dataset prep wmt_t2t_translate  error 

### ISSUE THREAD

**Issue by BhushanGarware** [GoogleCloudPlatform/t5x-on-vertex-ai#9]
`tfds build --data_dir $TFDS_DATA_DIR --experimental_latest_version wmt_t2t_translate`

(base) jupyter@t5x-vertex:~$ tfds build --data_dir $TFDS_DATA_DIR --experimental_latest_version wmt_t2t_translate
INFO[build.py]: Loading dataset wmt_t2t_translate from imports: tensorflow_datasets.translate.wmt_t2t
2023-07-27 13:34:22.706715: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-27 13:34:22.857667: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-27 13:34:22.859936: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-27 13:34:24.635615: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
INFO[dataset_info.py]: Load pre-computed DatasetInfo (eg: splits, num examples,...) from GCS: wmt_t2t_translate/de-en/1.0.0
INFO[dataset_info.py]: Load dataset info from /var/tmp/tmpdmnwqzhhtfds
INFO[dataset_info.py]: For 'wmt_t2t_translate/de-en/1.0.0': fields info.[description, config_name, config_description, citation, splits, supervised_keys, module_name] differ on disk and in the code. Keeping the one from code.
INFO[build.py]: download_and_prepare for dataset wmt_t2t_translate/de-en/1.0.0...
INFO[dataset_builder.py]: Generating dataset wmt_t2t_translate (gs://xmanager-bucket/datasets/wmt_t2t_translate/de-en/1.0.0)
Downloading and preparing dataset 1.61 GiB (download: 1.61 GiB, generated: Unknown size, total: 1.61 GiB) to gs://xmanager-bucket/datasets/wmt_t2t_translate/de-en/1.0.0...
INFO[wmt.py]: Using sub-datasets: {Split('train'): ['europarl_v7', 'commoncrawl', 'newscommentary_v13'], Split('validation'): ['newstest2013'], Split('test'): ['newstest2014']}
INFO[download_manager.py]: Downloading http://www.statmt.org/wmt13/training-parallel-europarl-v7.tgz into gs://xmanager-bucket/datasets/downloads/statmt.org_wmt13_traini-parall-europa-v71cKcs9sx8w9ctm8xHloEI83SJqzD7piDNK3xUXpQIB4.tgz.tmp.f62b7ef440aa40c39764a1d9cd826640...
Extraction completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [05:36<00:00, 42.10s/ file]
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 627/627 [05:36<00:00,  1.86 MiB/s]
Dl Completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [05:36<00:00, 336.83s/ url]
Extraction completed...: 0 file [00:00, ? file/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Dl Completed...: 0 url [00:00, ? url/s] ? file/s]
INFO[download_manager.py]: Downloading http://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz into gs://xmanager-bucket/datasets/downloads/statmt.org_wmt13_trainin-paralle-commoncl54tcDHJ3zCUVbW-zS8E004_IC4qlHH1DjAwfadBYe4.tgz.tmp.909b0f92e32e4fb6abb9afd0250854d5...
Extraction completed...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [07:20<00:00, 29.34s/ file]
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 875/875 [07:20<00:00,  1.99 MiB/s]
Dl Completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [07:20<00:00, 440.09s/ url]
Extraction completed...: 0 file [00:00, ? file/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]
Dl Completed...: 0 url [00:00, ? url/s] ? file/s]
INFO[download_manager.py]: Downloading http://data.statmt.org/wmt18/translation-task/training-parallel-nc-v13.tgz into gs://xmanager-bucket/datasets/downloads/data.stat.org_wmt1_tran-task_trai-para-nc-6LWgxBgzCHdv_LtotNmnXjpCH6OhzkF8D3v10aRrznA.tgz.tmp.45c5d4351b924eb99a557fdd36358b09...
INFO[download_manager.py]: Downloading http://data.statmt.org/wmt19/translation-task/dev.tgz into gs://xmanager-bucket/datasets/downloads/data.statmt.org_wmt19_translation-task_devO06xVjFNoHNOuXiBDkrIzPFeZSDrQnGJi3DabNFus9o.tgz.tmp.ff8c3e913d2545789dcc0fdb15742137...
Extraction completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 306/306 [01:46<00:00,  2.87 file/s]
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 143/143 [01:46<00:00,  1.34 MiB/s]
Dl Completed...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:46<00:00, 53.25s/ url]
Extraction completed...: 0 file [00:00, ? file/s]
INFO[wmt.py]: Using sub-datasets: {Split('train'): ['europarl_v7', 'commoncrawl', 'newscommentary_v13'], Split('validation'): ['newstest2013'], Split('test'): ['newstest2014']}
INFO[wmt.py]: Generating examples from: europarl_v7                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                        
  File "/opt/conda/bin/tfds", line 8, in <module>                                                                                                                                         
    sys.exit(launch_cli())
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/scripts/cli/main.py", line 109, in launch_cli
    app.run(main, flags_parser=_parse_flags)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/scripts/cli/main.py", line 104, in main
    args.subparser_fn(args)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/scripts/cli/build.py", line 305, in _build_datasets
    process_builder_fn(builder)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/scripts/cli/build.py", line 544, in _download_and_prepare
    builder.download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 166, in __call__
    return function(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 691, in download_and_prepare
    self._download_and_prepare(
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1583, in _download_and_prepare
    future = split_builder.submit_split_generation(
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/split_builder.py", line 341, in submit_split_generation
    return self._build_from_generator(**build_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/split_builder.py", line 406, in _build_from_generator
    for key, example in utils.tqdm(
  File "/opt/conda/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/translate/wmt.py", line 938, in _generate_examples
    for sub_key, ex in sub_generator(*files):
  File "/opt/conda/lib/python3.10/site-packages/tensorflow_datasets/translate/wmt.py", line 1000, in _parse_parallel_sentences
    assert f1_files and f2_files, "No matching files found: %s, %s." % (f1, f2)
AssertionError: No matching files found: gs://xmanager-bucket/datasets/downloads/extracted/TAR_GZ.statmt.org_wmt13_traini-parall-europa-v7AiTHxxDIoGPf2JOwzAgwIC1h9MdcF-uOMYNhA9J9luc.tgz/training/europarl-v7.de-en.de, gs://xmanager-bucket/datasets/downloads/extracted/TAR_GZ.statmt.org_wmt13_traini-parall-europa-v7AiTHxxDIoGPf2JOwzAgwIC1h9MdcF-uOMYNhA9J9luc.tgz/training/europarl-v7.de-en.en.

**Comment by RajeshThallam** [comment]
`tfds-nightly` seems to have issues. Please uninstall `tfds-nightly` and install tfds-datasets==4.7.0

```
pip uninstall tfds-nightly
pip install tensorflow-datasets==4.7.0
```
